elasticsearch-masters:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "es"
        node.name: "$${HOSTNAME}"
        node.data: "false"
        node.master: "true"
        network.host: "_site_"
elasticsearch-datanodes:
  metadata:
    elasticsearch:
      yml:
        cluster.name: "es"
        node.name: "$${HOSTNAME}"
        node.data: "true"
        node.master: "false"
        http.enabled: "false"
        network.host: "_site_"
elasticsearch-clients:
  metadata:
    elasticsearch:
      yml:
       cluster.name: "es"
       node.name: "$${HOSTNAME}"
       node.data: "false"
       node.master: "false"
       network.host: "_site_"
